// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WarehouseSystemAnalyst.Data.DataContext;

namespace WarehouseSystemAnalyst.Data.Migrations
{
    [DbContext(typeof(WarehouseDbContext))]
    [Migration("20201202113906_InitialDbCreation")]
    partial class InitialDbCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("MesureProductItem", b =>
                {
                    b.Property<int>("ProductItemsId")
                        .HasColumnType("int");

                    b.Property<string>("ProductItemsPK")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UnitOfMeusreId")
                        .HasColumnType("int");

                    b.Property<string>("UnitOfMeusrePK")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ProductItemsId", "ProductItemsPK", "UnitOfMeusreId", "UnitOfMeusrePK");

                    b.HasIndex("UnitOfMeusreId", "UnitOfMeusrePK");

                    b.ToTable("MesureProductItem");
                });

            modelBuilder.Entity("OrderOrderPallet", b =>
                {
                    b.Property<int>("OrderPalletsId")
                        .HasColumnType("int");

                    b.Property<int>("OrdersId")
                        .HasColumnType("int");

                    b.HasKey("OrderPalletsId", "OrdersId");

                    b.HasIndex("OrdersId");

                    b.ToTable("OrderOrderPallet");
                });

            modelBuilder.Entity("ProductProductItem", b =>
                {
                    b.Property<int>("ProductItemsId")
                        .HasColumnType("int");

                    b.Property<string>("ProductItemsPK")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.Property<string>("ProductsPK")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ProductItemsId", "ProductItemsPK", "ProductsId", "ProductsPK");

                    b.HasIndex("ProductsId", "ProductsPK");

                    b.ToTable("ProductProductItem");
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Entities.ContactEntities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PK")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("WarehouseItemId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Entities.Enrollment.Audit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("KeyValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Audits");
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Entities.MissionEntites.CollectItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("AssignedTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PK")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CollectItems");
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Entities.MissionEntites.CollectProductItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("AssignedTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PK")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CollectProductItems");
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Entities.MissionEntites.CollectProducts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("AssignedTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PK")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CollectProducts");
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Entities.PalletEntities.OrderPallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PalletCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PalletNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierPallet")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OrderPallet");
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Entities.PalletEntities.ProductPallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("BatcID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PalletCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PalletNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SupplierPallet")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BatcID");

                    b.HasIndex("ProductID");

                    b.ToTable("ProductPallets");
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Entities.ProductEntities.Batch", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("PK")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("BaseWarehouseId")
                        .HasColumnType("int");

                    b.Property<string>("BaseWarehousePK")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PalletID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductItemId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductSupplierID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StockInID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StockOutID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("WarehouseItemID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id", "PK");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasFilter("[Id] IS NOT NULL");

                    b.HasIndex("PK")
                        .IsUnique()
                        .HasFilter("[PK] IS NOT NULL");

                    b.HasIndex("ProductID");

                    b.HasIndex("ProductItemId");

                    b.HasIndex("StockInID");

                    b.HasIndex("StockOutID");

                    b.HasIndex("BaseWarehouseId", "BaseWarehousePK");

                    b.ToTable("Batches");
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Entities.ProductEntities.Category", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("PK")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubCategoryID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id", "PK");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasFilter("[Id] IS NOT NULL");

                    b.HasIndex("PK")
                        .IsUnique()
                        .HasFilter("[PK] IS NOT NULL");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Entities.ProductEntities.Mesure", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("PK")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductItemId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductMesureId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id", "PK");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasFilter("[Id] IS NOT NULL");

                    b.HasIndex("PK")
                        .IsUnique()
                        .HasFilter("[PK] IS NOT NULL");

                    b.ToTable("Mesures");
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Entities.ProductEntities.Package", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("PK")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductPackageID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id", "PK");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasFilter("[Id] IS NOT NULL");

                    b.HasIndex("PK")
                        .IsUnique()
                        .HasFilter("[PK] IS NOT NULL");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Entities.ProductEntities.Product", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("PK")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("BaseWarehouseId")
                        .HasColumnType("int");

                    b.Property<string>("BaseWarehousePK")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BatchID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("CollectProductsId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ItemID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MesureID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PalletID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductPackageID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductSupplierID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StockInID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StockOutID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id", "PK");

                    b.HasIndex("CategoryID");

                    b.HasIndex("CollectProductsId");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasFilter("[Id] IS NOT NULL");

                    b.HasIndex("PK")
                        .IsUnique()
                        .HasFilter("[PK] IS NOT NULL");

                    b.HasIndex("StockInID");

                    b.HasIndex("StockOutID");

                    b.HasIndex("BaseWarehouseId", "BaseWarehousePK");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Entities.ProductEntities.ProductItem", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("PK")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("AllocationId")
                        .HasColumnType("int");

                    b.Property<string>("BatcId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("BuyPricePerUnit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CollectProductItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Mesure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Metrial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductPackagesId")
                        .HasColumnType("int");

                    b.Property<string>("ProductPackagesPK")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("SellPricePerUnit")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id", "PK");

                    b.HasIndex("AllocationId");

                    b.HasIndex("CollectProductItemId");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasFilter("[Id] IS NOT NULL");

                    b.HasIndex("PK")
                        .IsUnique()
                        .HasFilter("[PK] IS NOT NULL");

                    b.HasIndex("ProductPackagesId", "ProductPackagesPK");

                    b.ToTable("ProductItems");
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Entities.ProductEntities.ProductMesures", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("PK")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MesureID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("QuantityPerUnit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitBuyPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitSellPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id", "PK");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasFilter("[Id] IS NOT NULL");

                    b.HasIndex("MesureID");

                    b.HasIndex("PK")
                        .IsUnique()
                        .HasFilter("[PK] IS NOT NULL");

                    b.HasIndex("ProductID");

                    b.ToTable("ProductMesures");
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Entities.ProductEntities.ProductPackages", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("PK")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PackageID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductItemID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WarehouseItemID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id", "PK");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasFilter("[Id] IS NOT NULL");

                    b.HasIndex("PK")
                        .IsUnique()
                        .HasFilter("[PK] IS NOT NULL");

                    b.HasIndex("PackageID");

                    b.HasIndex("ProductID");

                    b.ToTable("ProductPackages");
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Entities.ProductEntities.SubCategory", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("PK")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id", "PK");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasFilter("[Id] IS NOT NULL");

                    b.HasIndex("PK")
                        .IsUnique()
                        .HasFilter("[PK] IS NOT NULL");

                    b.ToTable("SubCategory");
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Entities.SupplyChainEntities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("AllocationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderPalletId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PK")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Entities.SupplyChainEntities.ProductVendor", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("PK")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("BatchId")
                        .HasColumnType("int");

                    b.Property<string>("BatchPK")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VendorID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id", "PK");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasFilter("[Id] IS NOT NULL");

                    b.HasIndex("PK")
                        .IsUnique()
                        .HasFilter("[PK] IS NOT NULL");

                    b.HasIndex("ProductID");

                    b.HasIndex("VendorID");

                    b.HasIndex("BatchId", "BatchPK");

                    b.ToTable("ProductVendors");
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Entities.SupplyChainEntities.Vendor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PK")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductVendorId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Entities.WarehouseEntites.Allocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("AllocationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PK")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("WarehouseItemID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AllocationId");

                    b.ToTable("Allocations");
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Entities.WarehouseEntites.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("BaseWarehouseId")
                        .HasColumnType("int");

                    b.Property<string>("BaseWarehousePK")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationColum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationRow")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationShelf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PK")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("WarehouseID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WarehouseItemID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BaseWarehouseId", "BaseWarehousePK");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Entities.WarehouseEntites.WarehouseItem", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("PK")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AllocationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AllocationWarehouseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BatchID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("CollectItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmployeeID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GoodsWarehouseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LocationID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PalletNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductMesureId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductMesuresId")
                        .HasColumnType("int");

                    b.Property<string>("ProductMesuresPK")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductPackageID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ShippingWarhouseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("WarehouseItemID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id", "PK");

                    b.HasIndex("AllocationId");

                    b.HasIndex("AllocationWarehouseId");

                    b.HasIndex("BatchID");

                    b.HasIndex("CollectItemId");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("GoodsWarehouseId");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasFilter("[Id] IS NOT NULL");

                    b.HasIndex("LocationID");

                    b.HasIndex("PK")
                        .IsUnique()
                        .HasFilter("[PK] IS NOT NULL");

                    b.HasIndex("ProductID");

                    b.HasIndex("ProductPackageID");

                    b.HasIndex("ShippingWarhouseId");

                    b.HasIndex("ProductMesuresId", "ProductMesuresPK");

                    b.ToTable("WarehouseItems");
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Implementation.BaseEntites.BaseStock", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("PK")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BatchID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("BatchQuantity")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsQuanityAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProductQuantity")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("TotalUnitsQuantity")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("WarehouseID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id", "PK");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasFilter("[Id] IS NOT NULL");

                    b.HasIndex("PK")
                        .IsUnique()
                        .HasFilter("[PK] IS NOT NULL");

                    b.ToTable("BaseStocks");

                    b.HasDiscriminator<string>("Discriminator").HasValue("BaseStock");
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Implementation.BaseEntites.BaseWarehouse", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("PK")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BatchID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WarehouseItemID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WarehouseName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id", "PK");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasFilter("[Id] IS NOT NULL");

                    b.HasIndex("PK")
                        .IsUnique()
                        .HasFilter("[PK] IS NOT NULL");

                    b.ToTable("Warehouses");

                    b.HasDiscriminator<string>("Discriminator").HasValue("BaseWarehouse");
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Entities.StockEntites.Inventory", b =>
                {
                    b.HasBaseType("WarehouseSystemAnalyst.Data.Implementation.BaseEntites.BaseStock");

                    b.Property<decimal>("ReorderLevel")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Inventory_ReorderLevel");

                    b.Property<decimal>("UnitsInOrder")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitsInStock")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Inventory_UnitsInStock");

                    b.HasDiscriminator().HasValue("Inventory");
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Entities.StockEntites.Stock", b =>
                {
                    b.HasBaseType("WarehouseSystemAnalyst.Data.Implementation.BaseEntites.BaseStock");

                    b.Property<decimal>("ReorderLevel")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitsInStock")
                        .HasColumnType("decimal(18,2)");

                    b.HasDiscriminator().HasValue("Stock");
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Entities.WarehouseEntites.WarehouseTypes.AllocationWarehouse", b =>
                {
                    b.HasBaseType("WarehouseSystemAnalyst.Data.Implementation.BaseEntites.BaseWarehouse");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int")
                        .HasColumnName("AllocationWarehouse_LocationId");

                    b.HasIndex("LocationId");

                    b.HasDiscriminator().HasValue("AllocationWarehouse");
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Entities.WarehouseEntites.WarehouseTypes.GoodsWarehouse", b =>
                {
                    b.HasBaseType("WarehouseSystemAnalyst.Data.Implementation.BaseEntites.BaseWarehouse");

                    b.HasDiscriminator().HasValue("GoodsWarehouse");
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Entities.WarehouseEntites.WarehouseTypes.ShippingWarehouse", b =>
                {
                    b.HasBaseType("WarehouseSystemAnalyst.Data.Implementation.BaseEntites.BaseWarehouse");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.HasIndex("LocationId");

                    b.HasDiscriminator().HasValue("ShippingWarehouse");
                });

            modelBuilder.Entity("MesureProductItem", b =>
                {
                    b.HasOne("WarehouseSystemAnalyst.Data.Entities.ProductEntities.ProductItem", null)
                        .WithMany()
                        .HasForeignKey("ProductItemsId", "ProductItemsPK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarehouseSystemAnalyst.Data.Entities.ProductEntities.Mesure", null)
                        .WithMany()
                        .HasForeignKey("UnitOfMeusreId", "UnitOfMeusrePK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OrderOrderPallet", b =>
                {
                    b.HasOne("WarehouseSystemAnalyst.Data.Entities.PalletEntities.OrderPallet", null)
                        .WithMany()
                        .HasForeignKey("OrderPalletsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarehouseSystemAnalyst.Data.Entities.SupplyChainEntities.Order", null)
                        .WithMany()
                        .HasForeignKey("OrdersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProductProductItem", b =>
                {
                    b.HasOne("WarehouseSystemAnalyst.Data.Entities.ProductEntities.ProductItem", null)
                        .WithMany()
                        .HasForeignKey("ProductItemsId", "ProductItemsPK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarehouseSystemAnalyst.Data.Entities.ProductEntities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId", "ProductsPK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Entities.PalletEntities.ProductPallet", b =>
                {
                    b.HasOne("WarehouseSystemAnalyst.Data.Entities.ProductEntities.Batch", "Batch")
                        .WithMany("Pallets")
                        .HasForeignKey("BatcID")
                        .HasPrincipalKey("PK");

                    b.HasOne("WarehouseSystemAnalyst.Data.Entities.ProductEntities.Product", "Product")
                        .WithMany("Pallets")
                        .HasForeignKey("ProductID")
                        .HasPrincipalKey("PK");

                    b.Navigation("Batch");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Entities.ProductEntities.Batch", b =>
                {
                    b.HasOne("WarehouseSystemAnalyst.Data.Entities.ProductEntities.Product", "Product")
                        .WithMany("Batches")
                        .HasForeignKey("ProductID")
                        .HasPrincipalKey("PK");

                    b.HasOne("WarehouseSystemAnalyst.Data.Entities.ProductEntities.ProductItem", "ProductItem")
                        .WithMany("Batches")
                        .HasForeignKey("ProductItemId")
                        .HasPrincipalKey("PK");

                    b.HasOne("WarehouseSystemAnalyst.Data.Entities.StockEntites.Stock", "StockIn")
                        .WithMany("Batches")
                        .HasForeignKey("StockInID")
                        .HasPrincipalKey("PK");

                    b.HasOne("WarehouseSystemAnalyst.Data.Entities.StockEntites.Inventory", "StockOut")
                        .WithMany("Batches")
                        .HasForeignKey("StockOutID")
                        .HasPrincipalKey("PK");

                    b.HasOne("WarehouseSystemAnalyst.Data.Implementation.BaseEntites.BaseWarehouse", null)
                        .WithMany("Batches")
                        .HasForeignKey("BaseWarehouseId", "BaseWarehousePK");

                    b.Navigation("Product");

                    b.Navigation("ProductItem");

                    b.Navigation("StockIn");

                    b.Navigation("StockOut");
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Entities.ProductEntities.Product", b =>
                {
                    b.HasOne("WarehouseSystemAnalyst.Data.Entities.ProductEntities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .HasPrincipalKey("PK");

                    b.HasOne("WarehouseSystemAnalyst.Data.Entities.MissionEntites.CollectProducts", null)
                        .WithMany("Items")
                        .HasForeignKey("CollectProductsId");

                    b.HasOne("WarehouseSystemAnalyst.Data.Entities.StockEntites.Stock", "StockIn")
                        .WithMany("Products")
                        .HasForeignKey("StockInID")
                        .HasPrincipalKey("PK");

                    b.HasOne("WarehouseSystemAnalyst.Data.Entities.StockEntites.Inventory", "StockOut")
                        .WithMany("Products")
                        .HasForeignKey("StockOutID")
                        .HasPrincipalKey("PK");

                    b.HasOne("WarehouseSystemAnalyst.Data.Implementation.BaseEntites.BaseWarehouse", null)
                        .WithMany("Products")
                        .HasForeignKey("BaseWarehouseId", "BaseWarehousePK");

                    b.Navigation("Category");

                    b.Navigation("StockIn");

                    b.Navigation("StockOut");
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Entities.ProductEntities.ProductItem", b =>
                {
                    b.HasOne("WarehouseSystemAnalyst.Data.Entities.WarehouseEntites.Allocation", "Allocation")
                        .WithMany()
                        .HasForeignKey("AllocationId");

                    b.HasOne("WarehouseSystemAnalyst.Data.Entities.MissionEntites.CollectProductItem", null)
                        .WithMany("Items")
                        .HasForeignKey("CollectProductItemId");

                    b.HasOne("WarehouseSystemAnalyst.Data.Entities.ProductEntities.ProductPackages", null)
                        .WithMany("ProductItems")
                        .HasForeignKey("ProductPackagesId", "ProductPackagesPK");

                    b.Navigation("Allocation");
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Entities.ProductEntities.ProductMesures", b =>
                {
                    b.HasOne("WarehouseSystemAnalyst.Data.Entities.ProductEntities.Mesure", "Mesure")
                        .WithMany("ProductMesures")
                        .HasForeignKey("MesureID")
                        .HasPrincipalKey("PK");

                    b.HasOne("WarehouseSystemAnalyst.Data.Entities.ProductEntities.Product", "Product")
                        .WithMany("Mesures")
                        .HasForeignKey("ProductID")
                        .HasPrincipalKey("PK");

                    b.Navigation("Mesure");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Entities.ProductEntities.ProductPackages", b =>
                {
                    b.HasOne("WarehouseSystemAnalyst.Data.Entities.ProductEntities.Package", "Package")
                        .WithMany("ProductPackages")
                        .HasForeignKey("PackageID")
                        .HasPrincipalKey("PK");

                    b.HasOne("WarehouseSystemAnalyst.Data.Entities.ProductEntities.Product", "Product")
                        .WithMany("ProductPackages")
                        .HasForeignKey("ProductID")
                        .HasPrincipalKey("PK");

                    b.Navigation("Package");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Entities.ProductEntities.SubCategory", b =>
                {
                    b.HasOne("WarehouseSystemAnalyst.Data.Entities.ProductEntities.Category", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .HasPrincipalKey("PK");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Entities.SupplyChainEntities.ProductVendor", b =>
                {
                    b.HasOne("WarehouseSystemAnalyst.Data.Entities.ProductEntities.Product", "Product")
                        .WithMany("ProductSuppliers")
                        .HasForeignKey("ProductID")
                        .HasPrincipalKey("PK");

                    b.HasOne("WarehouseSystemAnalyst.Data.Entities.SupplyChainEntities.Vendor", "Vendor")
                        .WithMany("ProductVendors")
                        .HasForeignKey("VendorID")
                        .HasPrincipalKey("PK");

                    b.HasOne("WarehouseSystemAnalyst.Data.Entities.ProductEntities.Batch", "Batch")
                        .WithMany("ProductSuppliers")
                        .HasForeignKey("BatchId", "BatchPK");

                    b.Navigation("Batch");

                    b.Navigation("Product");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Entities.WarehouseEntites.Allocation", b =>
                {
                    b.HasOne("WarehouseSystemAnalyst.Data.Entities.SupplyChainEntities.Order", "Order")
                        .WithMany("Allocations")
                        .HasForeignKey("AllocationId")
                        .HasPrincipalKey("PK");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Entities.WarehouseEntites.Location", b =>
                {
                    b.HasOne("WarehouseSystemAnalyst.Data.Implementation.BaseEntites.BaseWarehouse", null)
                        .WithMany("Locations")
                        .HasForeignKey("BaseWarehouseId", "BaseWarehousePK");
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Entities.WarehouseEntites.WarehouseItem", b =>
                {
                    b.HasOne("WarehouseSystemAnalyst.Data.Entities.WarehouseEntites.Allocation", "Allocation")
                        .WithMany("WarehouseItems")
                        .HasForeignKey("AllocationId")
                        .HasPrincipalKey("PK");

                    b.HasOne("WarehouseSystemAnalyst.Data.Entities.WarehouseEntites.WarehouseTypes.AllocationWarehouse", "AllocationWarehouse")
                        .WithMany("WarehouseItems")
                        .HasForeignKey("AllocationWarehouseId")
                        .HasPrincipalKey("PK");

                    b.HasOne("WarehouseSystemAnalyst.Data.Entities.ProductEntities.Batch", "Batch")
                        .WithMany("WarehouseItems")
                        .HasForeignKey("BatchID")
                        .HasPrincipalKey("PK");

                    b.HasOne("WarehouseSystemAnalyst.Data.Entities.MissionEntites.CollectItem", null)
                        .WithMany("Items")
                        .HasForeignKey("CollectItemId");

                    b.HasOne("WarehouseSystemAnalyst.Data.Entities.ContactEntities.Employee", "Employee")
                        .WithMany("WarehouseItems")
                        .HasForeignKey("EmployeeID")
                        .HasPrincipalKey("PK");

                    b.HasOne("WarehouseSystemAnalyst.Data.Entities.WarehouseEntites.WarehouseTypes.GoodsWarehouse", "GoodsWarehouse")
                        .WithMany("WarehouseItems")
                        .HasForeignKey("GoodsWarehouseId")
                        .HasPrincipalKey("PK");

                    b.HasOne("WarehouseSystemAnalyst.Data.Entities.WarehouseEntites.Location", "Location")
                        .WithMany("WarehouseItems")
                        .HasForeignKey("LocationID")
                        .HasPrincipalKey("PK");

                    b.HasOne("WarehouseSystemAnalyst.Data.Entities.ProductEntities.Product", "Product")
                        .WithMany("WarehouseItems")
                        .HasForeignKey("ProductID")
                        .HasPrincipalKey("PK");

                    b.HasOne("WarehouseSystemAnalyst.Data.Entities.ProductEntities.ProductPackages", "ProductPackage")
                        .WithMany("WarehouseItems")
                        .HasForeignKey("ProductPackageID")
                        .HasPrincipalKey("PK");

                    b.HasOne("WarehouseSystemAnalyst.Data.Entities.WarehouseEntites.WarehouseTypes.ShippingWarehouse", "ShippingWarehouse")
                        .WithMany("WarehouseItems")
                        .HasForeignKey("ShippingWarhouseId")
                        .HasPrincipalKey("PK");

                    b.HasOne("WarehouseSystemAnalyst.Data.Entities.ProductEntities.ProductMesures", "ProductMesures")
                        .WithMany()
                        .HasForeignKey("ProductMesuresId", "ProductMesuresPK");

                    b.Navigation("Allocation");

                    b.Navigation("AllocationWarehouse");

                    b.Navigation("Batch");

                    b.Navigation("Employee");

                    b.Navigation("GoodsWarehouse");

                    b.Navigation("Location");

                    b.Navigation("Product");

                    b.Navigation("ProductMesures");

                    b.Navigation("ProductPackage");

                    b.Navigation("ShippingWarehouse");
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Entities.WarehouseEntites.WarehouseTypes.AllocationWarehouse", b =>
                {
                    b.HasOne("WarehouseSystemAnalyst.Data.Entities.WarehouseEntites.Location", null)
                        .WithMany("GoodsPickings")
                        .HasForeignKey("LocationId");
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Entities.WarehouseEntites.WarehouseTypes.ShippingWarehouse", b =>
                {
                    b.HasOne("WarehouseSystemAnalyst.Data.Entities.WarehouseEntites.Location", null)
                        .WithMany("GoodsShippings")
                        .HasForeignKey("LocationId");
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Entities.ContactEntities.Employee", b =>
                {
                    b.Navigation("WarehouseItems");
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Entities.MissionEntites.CollectItem", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Entities.MissionEntites.CollectProductItem", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Entities.MissionEntites.CollectProducts", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Entities.ProductEntities.Batch", b =>
                {
                    b.Navigation("Pallets");

                    b.Navigation("ProductSuppliers");

                    b.Navigation("WarehouseItems");
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Entities.ProductEntities.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Entities.ProductEntities.Mesure", b =>
                {
                    b.Navigation("ProductMesures");
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Entities.ProductEntities.Package", b =>
                {
                    b.Navigation("ProductPackages");
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Entities.ProductEntities.Product", b =>
                {
                    b.Navigation("Batches");

                    b.Navigation("Mesures");

                    b.Navigation("Pallets");

                    b.Navigation("ProductPackages");

                    b.Navigation("ProductSuppliers");

                    b.Navigation("WarehouseItems");
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Entities.ProductEntities.ProductItem", b =>
                {
                    b.Navigation("Batches");
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Entities.ProductEntities.ProductPackages", b =>
                {
                    b.Navigation("ProductItems");

                    b.Navigation("WarehouseItems");
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Entities.SupplyChainEntities.Order", b =>
                {
                    b.Navigation("Allocations");
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Entities.SupplyChainEntities.Vendor", b =>
                {
                    b.Navigation("ProductVendors");
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Entities.WarehouseEntites.Allocation", b =>
                {
                    b.Navigation("WarehouseItems");
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Entities.WarehouseEntites.Location", b =>
                {
                    b.Navigation("GoodsPickings");

                    b.Navigation("GoodsShippings");

                    b.Navigation("WarehouseItems");
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Implementation.BaseEntites.BaseWarehouse", b =>
                {
                    b.Navigation("Batches");

                    b.Navigation("Locations");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Entities.StockEntites.Inventory", b =>
                {
                    b.Navigation("Batches");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Entities.StockEntites.Stock", b =>
                {
                    b.Navigation("Batches");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Entities.WarehouseEntites.WarehouseTypes.AllocationWarehouse", b =>
                {
                    b.Navigation("WarehouseItems");
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Entities.WarehouseEntites.WarehouseTypes.GoodsWarehouse", b =>
                {
                    b.Navigation("WarehouseItems");
                });

            modelBuilder.Entity("WarehouseSystemAnalyst.Data.Entities.WarehouseEntites.WarehouseTypes.ShippingWarehouse", b =>
                {
                    b.Navigation("WarehouseItems");
                });
#pragma warning restore 612, 618
        }
    }
}
